### ISSUE TITLE
Provide a Way to Remove Callbacks in WebTerminal API

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/webterminal#108]
Terminal API functions onOutput, onUserInput and execute (#107) are invoking callbacks, but there may be a need to stop triggering them at some point.

Provide some API to remove callbacks.

Info @wcjphoenix

**Comment by wcjphoenix** [comment]
Why do you need to stop them from triggering?

**Comment by ZitRos** [comment]
@wcjphoenix, pne of the examples, I thought that when the user completes a task in your project, you may want to stop callback from happening. This is all about providing the complete pub-sub pattern. In JavaScript, for example, everywhere where you have .addEventListener, you also have .removeEventListener, so the WebTerminal should have.

**Comment by ZitRos** [comment]
Actually I made a little design mistake, I should have named the functions differently: `.on("input", options, callback)` and `.on("output", options, callback)` to certainly match all JavaScript conventions. Also this is much better to read and expand.
What if we change the names, Walter? This will be the major breaking change, so maybe it is not worth it or at least, should wait until the next major WebTerminal update (which may happen as a result of #103).

**Comment by wcjphoenix** [comment]
I think it would be good to wait until the next update, but thanks for the explanation about the reasoning behind a remove function.

**Comment by ZitRos** [comment]
Done by af4c5641cebe52f4f736c82f58d76f3bb650f38b. I also updated WebTerminal global versions and added docs. If you have any further questions or suggestions, please tell me! Thanks!
