### ISSUE TITLE
4.6.1 - Multiple Issues

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-ru/webterminal#109]
$ZV = **Cache for Windows (x86-64) 2016.2.1 (Build 806_0_17136U) Tue Mar 7 2017 12:25:45 EST** _and_ **Cache for Windows (x86-64) 2017.1 (Build 792U) Mon Mar 20 2017 19:13:14 EDT**

Browser: **Google Chrome Version 59.0.3071.115 (Official Build) (32-bit)**
OS: **Windows 7 Home Premium SP1**

Multiple issues with latest release ...

1. In-place Update generates the following without completing the update:

> URL: https://intersystems-ru.github.io/webterminal/files/WebTerminal-v4.6.1.xml
Requesting server to update...
Update started, please, do not close this window.
Requesting https://intersystems-ru.github.io/webterminal/files/WebTerminal-v4.6.1.xmlResponse downloaded.
ERROR #6156: No match between server name 'intersystems-ru.github.io' and SSL certificate values 'opensource.guide,www.opensource.guide'.

2. Download and Import (via Studio) of **WebTerminal-v4.6.1.xml** generates these two attached error dialogs:
<img width="348" alt="webterminal01" src="https://user-images.githubusercontent.com/4532366/28239031-c6b915e8-692f-11e7-8910-d150b3669b66.png">
<img width="348" alt="webterminal02" src="https://user-images.githubusercontent.com/4532366/28239032-c6b9d848-692f-11e7-99dd-d714098a3c35.png">

The import appears to complete and compile, however, and the new version number displays upon starting a new session.

3. Command line will randomly ignore keyboard input other than [Enter]. A browser refresh fixes the problem at the expense of your current session. Still attempting to determine what triggers this.

I still love it, though 😀

**Comment by ZitRos** [comment]
Hello! Wow. Thanks for reporting this.

> ERROR #6156: No match between server name 'intersystems-ru.github.io' and SSL certificate values 'opensource.guide,www.opensource.guide

1. Currently I have the same issue. It looks like a temporary issue, it should not persist for a long time. Looking for the others...

**Comment by ZitRos** [comment]
Regarding to 2, try moving the `XML` file to any path which does not contain non-latin characters.

**Comment by ZitRos** [comment]
Regarding to 3, if it is not vanished by 2, try different browser and tell me if it works! Also please tell which browser do you use. Thanks!

**Comment by DodgeDeBoulet** [comment]
Re: #2 - The path contains no non-Latin characters. It is, however, a "virtual drive" mounted from a VMWare 12.x virtual machine (the host on which Caché is running is a VM). From Studio's perspective, the path is **Z:\DDownloads\Intersystems**. Copying the file to a local path (**C:\Intersystems**) and importing it generates the same error.

Re: #3 - I've updated the original issue report with the browser information (**Google Chrome Version 59.0.3071.115 (Official Build) (32-bit)**). This issue did not occur with that browser previously. I will try Firefox next.

**Comment by ZitRos** [comment]
> I will try Firefox next.

Please. I have the exact same version of Chrome browser and no issues with the input. Maybe its an issue with virtual machine keyboard emulation?

Talking about 2, try to import WebTerminal, for example, [from default terminal by executing](http://intersystems-ru.github.io/webterminal/#docs.1.1.1):

```
do $system.OBJ.Load("/path/to/xml/file/WebTerminal-4.6.1.xml","ck")
```

**Comment by DodgeDeBoulet** [comment]
Re: 2 - Loading from default terminal instead of Studio, everything looks good:
```
HICG>do $system.OBJ.Load("C:\Intersystems\WebTerminal-v4.6.1.xml","ck")
 
Load started on 07/15/2017 09:47:10
Loading file C:\Intersystems\WebTerminal-v4.6.1.xml as xml
Imported class: WebTerminal.Analytics
Imported class: WebTerminal.Autocomplete
Imported class: WebTerminal.Common
Imported class: WebTerminal.Core
Imported class: WebTerminal.Engine
Imported class: WebTerminal.ErrorDecomposer
Imported class: WebTerminal.Handlers
Imported class: WebTerminal.Installer
Imported class: WebTerminal.Router
Imported class: WebTerminal.StaticContent
Imported class: WebTerminal.Trace
Imported class: WebTerminal.Updater
Compiling 12 classes, using 2 worker jobs
Compiling class WebTerminal.Analytics
Compiling class WebTerminal.Common
Compiling class WebTerminal.ErrorDecomposer
Compiling class WebTerminal.Handlers
Compiling class WebTerminal.StaticContent
Compiling class WebTerminal.Updater
Compiling class WebTerminal.Autocomplete
Compiling class WebTerminal.Core
Compiling class WebTerminal.Trace
Compiling class WebTerminal.Router
Compiling class WebTerminal.Engine
Compiling routine WebTerminal.Analytics.1
Compiling routine WebTerminal.Common.1
Compiling routine WebTerminal.ErrorDecomposer.1
Compiling routine WebTerminal.StaticContent.1
Compiling routine WebTerminal.Updater.1
Compiling routine WebTerminal.Handlers.1
Compiling routine WebTerminal.Core.1
Compiling routine WebTerminal.Router.1
Compiling routine WebTerminal.Trace.1
Compiling routine WebTerminal.Autocomplete.1
Compiling routine WebTerminal.Engine.1
Recompiling WebTerminal, skipping the deletion...
Compiling class WebTerminal.Installer
Compiling routine WebTerminal.Installer.1
Installing WebTerminal application to HICG
Updating web application "/terminal"...
WEB application "/terminal" is updated.
Updating web application "/terminalsocket"...
WEB application "/terminalsocket" is updated.
Mapping %WebTerminal package into all namespaces: %All SAMPLES DOCBOOK
WebTerminal package successfully mapped into all namespaces.
Load finished successfully.
```

**Comment by ZitRos** [comment]
Good. So there is no reason to worry about WebTerminal installer, it was probably a Studio issue.

Let's see if **1** will get fixed by time, if not, I will look closer. The strange part is that I did no changes in WebTerminal installer, and the code works properly from terminal, but does not work from Caché process. Will see.

**Comment by DodgeDeBoulet** [comment]
Thanks for looking into this so quickly. I'll continue to experiment with Firefox to see if item 3 changes in behavior.

**Comment by DodgeDeBoulet** [comment]
Re: Item 3 - One instance where this seems to occur is when I've resumed the virtual machine after suspending it. Pressing the [Enter] key displays another prompt, but no other keyboard input is accepted. It's quite possible that my session was somehow lost or timed out due to the suspension of the VM, but I would think WebTerminal should (somehow) sense that.
I'm guessing the same thing might occur with a non-virtual host if it's suspended or hibernated for some period of time.

**Comment by ZitRos** [comment]
Just tried 3 (hibernating) on my laptop, no luck in reaching this issue... If you are experienced in JavaScript, you can try to see what's wrong, for example:

1. Try executing `document.querySelector("textarea").addEventListener("keypress", ({ keyCode }) => console.log(keyCode));` in the browser's console, and see if pressing on keyboard keys yields any output when terminal input is focused. If no output appears, that's not a WebTerminal problem, but platform's.
2. Open developer tools sources, find `terminal/js/index.js` file there, format it to more readable form with Chrome "Pretty Print" option, search for exact this string `input.addEventListener("input"`, and place a break point on the right next line after one you've found. Now press any key that didn't work - if debugger does not stop at breakpoint, that's not a WebTerminal problem. Most likely platform's one.

In other case I will be happy to investigate the problem in WebTerminal :)

**Comment by ZitRos** [comment]
Closed due to inactivity.

If the issue still present, please, comment or re-open it. Also please, potentially, check whether any Chrome plugins cause the problems.
