### ISSUE TITLE
Error syntax highlighting in SQL mode.

### ISSUE THREAD

**Issue by MakarovS96** [intersystems-ru/webterminal#110]
Does not recognize aliases in the update query.
![sql_syntax_error](https://user-images.githubusercontent.com/19629483/28613911-952c5032-71fc-11e7-8016-37e1deac7cf7.png)

**Comment by ZitRos** [comment]
Thanks! Will look at this on the week.

**Comment by ZitRos** [comment]
Now it should work. Thanks for reporting!
