### ISSUE TITLE
Terminal fails to update with /update command

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/webterminal#33]
This command throws different errors in Caché 2014/2015.

2014
<code>ERROR #5809: Object to Load not found, class '%Dictionary.CompiledProperty', ID '%CSP.WebSocket||WSClassProtocolVersion'</code>

2015
<code>&lt;Status OK, but loads nothing&gt;</code>

Probably the algorithm is wrong:
   1. Write temporary xml file to disk from WEB using <code>do file.CopyFrom(httprequest.HttpResponse.Data)</code>;
   2. Perform <code>do $System.OBJ.ImportDir(path, "terminal_update.temp.xml", "ckbud", .error, 1)</code> to import new code;
   3. Remove temporary file.

Any suggestions are welcome.

**Comment by deadpadre** [comment]
I'm getting __Fail__ message on the *Clearing temporary files* stage (updating from 0.4 to 0.6, 2015.2). Is that the issue you're talking about?

**Comment by ZitRos** [comment]
@deadpadre, Exactly.

It seems that something wrong with <code>do file.CopyFrom(httprequest.HttpResponse.Data)</code> method, new file has 1 wrong symbol.

There are also familiar issue with <code>#define</code>'d values in Caché 2014/2015 that crashes (any) installation process executed in CWT.

So I (we) are searching ways to fix it, but this task is not under priority now. We hope to find solution as soon as possible.

By the way, until terminal v2 release (not beta) you have to update terminal manually.

If you have any issues or suggestions, please, feel free to post them here, on our issue tracker, Thank you!

**Comment by ZitRos** [comment]
Finally fixed by 01efec6d217d842f85086e0a0cf1a15c9c11d92f.
