### ISSUE TITLE
Terminal fails with autocomplete

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/webterminal#35]
version 2.0.0.5
https://www.dropbox.com/s/sy6ut5ig70ns18p/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-06%2019.25.04.png?dl=0

It builds something but it doesn't work further.

**Comment by ZitRos** [comment]
Does the direct request to this file from browser returns file contents?
Does the <code>/InterSystems/Cache/CSP/sys/WebTerminal/js/autocomplete/*</code> files really exists?
Are there any errors in browser's console?

The answers for this questions will help me to understand the problem.

Thank you!

**Comment by ZitRos** [comment]
Solved with c27efaf88b951d0023555039c34da29c42d3c122,
