### ISSUE TITLE
Installed url and usage url are not the equal

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/webterminal#37]
The Caché WEB terminal v2.0.0-beta.8 version installs web terminal so that the app should be called by

...port/csp/sys/webterminal/index.CSP

but in Usage now we see https://github.com/intersystems-ru/webterminal
...[port]/csp/sys/WebTerminal/index.csp.

Is it possible to make the url in lower case all? Like this?
...port/csp/sys/webterminal/index.csp

**Comment by ZitRos** [comment]
@evshvarov, Probably your Caché has cached index.CSP file in a way I do not know how. Did you install CWT to this installation before? The "bare" installation should not make extension of the file uppercase, and also all of my 3 Caché installations have lowercase extension.

**Comment by ZitRos** [comment]
Within the latest version, the URL is always `[server]:[port]/terminal/`.

**Comment by evshvarov** [comment]
Wonderful!

среда, 9 декабря 2015 г. пользователь Nikita написал:

**Comment by evshvarov** [comment]
How about release?

**Comment by eduard93** [comment]
When REST support is tested I suppose?

**Comment by ZitRos** [comment]
@evshvarov,

> How about release?

The release has came! Download it from [GitHub](https://github.com/intersystems-ru/webterminal/releases/tag/3.1.4) or [Project page](http://intersystems-ru.github.io/webterminal/#downloads).

**Comment by ZitRos** [comment]
@eduard93, in general, only the mapping mechanism should be tested well, so let's go on! Web Terminal core is almost the same, except of the minor fixes.

I will be happy to hear any issues or enhancements.
