### ISSUE TITLE
If you deal with a long command in CWT cursor "losts" the right position

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/webterminal#38]
Suppose you have the command
set a="aaaaaaaaaaaaaaaaaaaaaaa",b="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",c="cccccccccccccccccccccccc"
run it and then get from history and try to change c variable to d.  I have mispositioning on Mac Chrome

**Comment by ZitRos** [comment]
This is the one of the minor known bugs, thank you.

**Comment by ZitRos** [comment]
Not a bug for the [latest](http://intersystems-ru.github.io/webterminal/#downloads) versions of CWTv4.
