### ISSUE TITLE
Enable custom title

### ISSUE THREAD

**Issue by antonum** [intersystems-ru/webterminal#39]
Make page title configurable, so user can set arbitrary title via global.

Right now title is hardcoded to ”Cach&eacute; WEB Terminal” and if working with multiple Cache' instances it's impossible to differentiate one instance's terminal from another.

Summary of the enhancement:
&lt;title&gt;#($g(^global,”Cach&amp;eacute; WEB Terminal”)#&lt;/title&gt;

We can optionally autogenerate title based on instance name, but one should be able to override it - autogenerated title based on server address or instance name would be useless in the situations like multiple identical instances (ECP App servers) in the cloud. Titles like DBSERVER, APPSERVERn would be more appropriate.

**Comment by evshvarov** [comment]
Pull request?

**Comment by ZitRos** [comment]
@antonum, done with 22134e7e14c558ab6cd720f52e06c478781a63bd.

Please, update with `/update` command (if your CWT version is greater than 3.1.4) or download the latest release from [the project page](http://intersystems-ru.github.io/webterminal/#downloads).

The usage of `/rename` command you can find in `/help`.

If this feature was implemented not as expected, please, reopen the issue or submit a new one.

Have a nice holidays!
