### ISSUE TITLE
WebTerminal plugins

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/webterminal#40]
How about to let people make WEB Terminal plugins? Having WebTerminal API made, I see the good way for people to contribute their own features and applications like #32 specifically for WebTerminal.

Plugin will consist of two parts: `client` and `server (optional)` code. It can both extend client functionality by adding, f.e. new commands or GUI features, and also implement any server-side handlers.

This requires a good WebTerminal API, by the way, but I see all this quite implementable.

**Comment by eduard93** [comment]
Where's API specks?

**Comment by ZitRos** [comment]
@eduard93, API specs don't exists yet, just turn on your imagination! :blush: This discussion should answer a question if we need a CWT plugin mechanism to be build at all, not focusing on the technical details, and is there anybody interested in extending CWT functionality in that way.

Talking about API, suggesting in short:
From the client side, there will be full access to DOM and core terminal elements as well as print(), prompt() functions, etc.
From the server [optional] side, I think, there's almost one purpose to call server-side methods stored inside custom class. `WebTerminal/Plugins/*.cls` with any required methods implemented such as onSessionBegin(), onSessionEnd(), onMessage(), onCustomMessage(), etc.

Also, after people find plugins useful, it will be a good idea to make plugin mechanism a little global like [CPM](https://github.com/intersystems-ru/CPM) do, by adding in-terminal commands like `/plugins` (lists available plugins), `/plugins install ...` `/plugins uninstall ...`.

**Comment by ZitRos** [comment]
Closed for now. The "plugins" functionality should go with the package manager.
