### ISSUE TITLE
Refactoring of WebTerminal.Engine class

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/webterminal#43]
I propose refactoring of WebTerminal.Engine class into following classes:
- WebTerminal.Parameters - contains parameters
- WebTerminal.Redirects - extends %Library.Routine and contains methods working with redirects
- WebTerminal.Actions - contains user actions (ExecuteCommand, ExecuteSQL Update, Tracking etc)
- WebTerminal.Autocomplete - contains autocomplete logic
- WebTerminal.Engine - extends all previous classes, contains OnMethods, Server, ClientLoop

I'm not sure about exact class structure, but that's the gist of it.
Would make for an easier reading.

**Comment by eduard93** [comment]
Also WebTerminal.Actions would be testable in terminal (usual) context. Maybe.

**Comment by ZitRos** [comment]
> WebTerminal.Engine - extends all previous classes

`WebTerminal.Engine` extends `%CSP.WebSocket`, which is an important point - all previous classes should be encapsulated inside Engine class to have ability to interact with the client.

Refactoring is always a good idea, Edward!

P.S. Renaming classes (or creating a new ones) has a downbeat effect on the terminal's `/update` command right now. Somewhere in the heaven the `RemoveProjection` method of `WebTerminal.Installer` class should be aware of all the terminal's classes to remove, and **has to be aware** of the namespace CWT installed to by user, which is not implemented for now. In case of user remove classes from the namespace classes were once mapped to, `WebTerminal.Installer` won't know the "original" namespace. Any ideas how to deal with all of this?

**Comment by eduard93** [comment]
> has to be aware of the namespace CWT installed to by user

Follow the mappings :)

**Comment by ZitRos** [comment]
> They point to database associated with namespace we need

The only thing mappings tell us is the database where package is stored. But how to get the namespace? Well, it is a database property to have a default namespace, and not vice versa, isn't it?

**Comment by eduard93** [comment]
You can use Config.Namespaces:List query and iterate over it till you find first namespace pointing to this database.
Since Namespace count does not usually go higher than lower hundreds it would not be a time-consuming operation.

**Comment by ZitRos** [comment]
> You can use Config.Namespaces:List query and iterate over it till you find first namespace pointing to this database.

But what if two namespaces point to the same database?

**Comment by eduard93** [comment]
>But what if two namespaces point to the same database?
So? Any will do.

**Comment by ZitRos** [comment]
Does the class unique for a namespace or a database? Your answer likely tells the last variant correct, right?

**Comment by eduard93** [comment]
Namespace stores classes in routines database. So the class is unique for a namespace.
Class is also unique for a database, because class, like everything else is a global (Class definition = subscript node in ^oddDEF global).
So both are correct. Class is unique for a namespace and a database

**Comment by ZitRos** [comment]
> Config.Namespaces:List query

OK, I'll try.

**Comment by eduard93** [comment]
Do you want to focus on other issues? I can take this one.

**Comment by ZitRos** [comment]
Do you want to take the last issue discussed (always correct deleting and unmapping) issue, or a full refactoring phase? In case of the last one, I think it is better for me first to redefine how classes inside repository are stored with a simple gulp task to collect them into one project.

**Comment by eduard93** [comment]
The second one. Yes, please do redefine how classes inside repository are stored.

**Comment by eduard93** [comment]
About first. get db via w ##class(%SYS.Namespace).GetPackageDest($Namespace,"WebTerminal")

**Comment by eduard93** [comment]
About first. [Here's](http://code.intersystems.com/code/Code.View.Code.cls?ID=888) get original namespace method

**Comment by ZitRos** [comment]
> Yes, please do redefine how classes inside repository are stored.

Ready with 1bded7c11b4f82540648a2bd58fd90e50d5c5e2c. The primary concepts and "how to"s I have placed inside `DEVELOPMENT.md` file.

**Comment by ZitRos** [comment]
> About first. Get db via w ##class(%SYS.Namespace).GetPackageDest($Namespace,"WebTerminal")

> About first. Here's get original namespace method

Which one? :)

**Comment by eduard93** [comment]
The second one. ##class(%SYS.Namespace).GetPackageDest($Namespace,"WebTerminal")``` only returns db fath. The second one returns namespace

**Comment by ZitRos** [comment]
@eduard93, I was sure that I left a comment here saying that everything is ready but I cannot find it again, so:

I did the repository refactoring by 1bded7c11b4f82540648a2bd58fd90e50d5c5e2c, so now it is OK to go forward with WebTerminal.Engine class refactoring. Read the `DEVELOPMENT.md` notes also.

Thank you!

**Comment by eduard93** [comment]
I'm refactoring all right, see https://github.com/intersystems-ru/webterminal/tree/Refactoring branch. It's just currently refactoring broke my local webterminal, so I'm not commiting.

**Comment by eduard93** [comment]
What does Trace methods do? How do I test it?

**Comment by eduard93** [comment]
Encounering clean install compilation problems

**Comment by eduard93** [comment]
Use DependsOn instead of CompileAfter seems to solve compilation errors on import See https://github.com/intersystems-ru/webterminal/commit/6d8de5f71c845fd3097df3505bb7a7cc7320c1a5

**Comment by ZitRos** [comment]
I have tested these changes and everything seem to be OK. The installer issue now has it's place here: #46. Thanks Edward!
