### ISSUE TITLE
% global rename

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/webterminal#44]
^%WebTerminal globals should now be called ^WebTerminal I suppose

**Comment by eduard93** [comment]
Ah, they would not be availible in other ns then

**Comment by eduard93** [comment]
Or you would require global mapping to %All

**Comment by ZitRos** [comment]
Right, the idea is to have a "global" global ^% to make it available from anywhere. Not sure about idea to map all the globals through namespaces.

**Comment by eduard93** [comment]
To write ^% globals you need write access to CACHESYS database (which is usually %DB_CACHESYS resource).

**Comment by ZitRos** [comment]
I saw in documentation that there's a way to map exact global into all namespaces. I'll check this later.

**Comment by ZitRos** [comment]
Done with 0d82f6302d235a3ca6c1bfc66f960fb9b9d7ef1f.
