### ISSUE TITLE
Problem with installation not from Studio

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/webterminal#49]
Tried to install from class Explorer in Management Portal.
Imported file and then there were some errors during compilation.

System is Cache 2015.1 on Linux.
Then I tried to do 'normal' installation through Studio and compilation went with no problems though app doesn't work. I have 401 error when go to server/terminal/

Would it be possible to support this type of installation?
What should I do now to let webterminal work?

**Comment by eduard93** [comment]
Errorlog?

**Comment by eduard93** [comment]
Does /terminal web app exist on server?

**Comment by ZitRos** [comment]
> I have 401 error when go to server/terminal/

It seems like this is an expected result - did you ever authorize on that server? The WEB application is protected by password by default, you should renew the session.

> Would it be possible to support this type of installation?

It must work smoothly at least on Caché 2013.1-2015.3.

Try
1. Check if you ever installed web terminal on this server. Web terminal versions and mapping will conflict in case of wrong removal;
2. Remove terminal package and try importing it again.

> there were some errors during compilation

It will be extremely useful if you post a **compilation log** here for both compilation cases, that is almost all that tells the problem.

**Comment by eduard93** [comment]
It was a server issue, closed.
