### ISSUE TITLE
Remove WebTerminal.prj  project from xml

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/webterminal#52]
Update fails cause it can't overwrite existing project with the same name. 
I removed it manually and it was ok, but I'd rather remove WebTerminal.prj

**Comment by ZitRos** [comment]
I have never had issues with the "integrated" project updating terminal, but anyway it's fine to remove *.prj.

What system are you trying to update terminal from? Could you please provide some update logs/errors when it fails?

**Comment by eduard93** [comment]
It's %Studio.Project throwing $$$ERROR($$$DuplicatedName,i) I think.

**Comment by ZitRos** [comment]
Done bbc1915bfebb676e5b49fc2be5a3812b8e09d045. Do you think this issue should be pushed as a `/update`? I never encourage it so I don't know which priority should it take.

**Comment by eduard93** [comment]
Low; possibly related to install from management portal (it's the same server)

**Comment by eduard93** [comment]
I don't see the need to separate this as an `/update`

**Comment by ZitRos** [comment]
OK - it will come with the next release. Thanks.
