### ISSUE TITLE
webterminal does not work with Cache 2016.1.0 and later

### ISSUE THREAD

**Issue by Maxabrahams** [intersystems-ru/webterminal#53]
cache2016.1.0 is not released yet, but I thought you'd want to know that you get a code 1006 from websockets immediately upon entering credentials into host:port/terminal/

I love the tool, thanks for your hard work in creating it.

**Comment by ZitRos** [comment]
Hello, thanks for the issue report!

It's one of the known problems with WebTerminal for now, I'll try to find a solution soon.

**Comment by ZitRos** [comment]
Done! Now WebTerminal is friendly with Caché 2016.*. Please, download the latest version () from [here](http://intersystems-ru.github.io/webterminal/#downloads), it has to work. If something goes wrong, reopen this issue.

**Below I will describe in short how WebSockets work in InterSystems Caché 2016.* for the user.**

They work in a strange way. The pretty normal part for Caché is the next: for establishing connection to any WebSocket \*class* we **have to have** (before 2016.1 it was optional) a web application without authentication set up, referring the namespace where our \*class* is located. In other words, if we have `Class Test.WebSocket Extends %CSP.WebSocket`, then we need ANY public (non-authenticated) WEB application to be set up to connect to our class.

The only thing documentation says is that we can connect using this URL (for example, connect to `Test.WebSocket` in `USER` namespace): `ws://host:port/csp/user/Test.WebSocket.cls`. That is OK until `csp/user` WEB application exists. Removing this application will crash this method.

Users can create a new namespace without the default WEB application in this namespace, and this automatically means that users have no ways to connect to their WebSocket application there.

Furthermore, there are a lot of strange things: when such application exists, we can (!) establish a connection to `ws://host:port/csp/user/Test.WebSocketClassNameThatDoesNotEvenExists.cls`, this connection will be successfully opened and nothing more (`test3` is a web app on the screenshot):
![image](https://cloud.githubusercontent.com/assets/4989256/12869132/e6911158-cd1e-11e5-8c6b-aeb87bc64681.png)

Furthermore x2, assigning "Dispatch class" to the WEB application (f.e. `/csp/user`) will also make the socket unavailable.

**So**

The solution for terminal were just to create yet another "empty" WEB application named `/terminalsocket`, and replace the connection URL to `ws://host:port/terminalsocket/WebTerminal.Engine.cls`. That is the only way I find usable.

**Comment by eduard93** [comment]
Have you tried adding db access roles to `/terminal` webapp  and set it with unauth&auth access ?

**Comment by ZitRos** [comment]
@eduard93, I tried almost everything. Try it yourself ;) Setting the dispatch class makes this app "invisible" for WebSocket connection.

**Comment by eduard93** [comment]
@ZitRos Sorry, I forgot about REST.
