### ISSUE TITLE
Required application roles on install with Normal security settings

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/webterminal#54]
App: `/terminalsocket` in USER namespace requires `%DB_CACHESYS` and `%DB_USER` so UnknownUser can access it.

Here's an audit message without `%DB_CACHESYS` so we can maybe remove the dependency. Namespace routines db needs to have public RW (maybe R is enough?) resource, or if not, role given to web app.

Audit Details:
Description 	Attempt to access a protected resource
Timestamp 	2016-02-12 16:05:09.226
UTCTimestamp 	2016-02-12 21:05:09.226
Event Source 	%System
Event Type 	%Security
Event 	Protect
Username 	UnknownUser
Pid 	23104
JobId 	2424862
JobNumber 	30
IP Address 	
Executable 	CSPap.so
System ID 	
Index 	16384
Roles 	%DB_%DEFAULT,%DB_CACHE,%DB_USER
Authentication 	Unauthenticated
Namespace 	USER
Routine 	zRequireAuthorization+19^WebTerminal.Engine.1 |"^^/InterSystems/Cache/mgr/user/"|
User Info 	
O/S Username 	CSP Gateway
Status 	
Event Data 	<PROTECT>zRequireAuthorization+19^WebTerminal.Engine.1 */InterSystems/Cache/mgr/

**Comment by eduard93** [comment]
Oh, of course  `zRequireAuthorization+19^WebTerminal.Engine.1`:
```
zn "%SYS"
do ##class(Security.Users).Get(username, .userProps)
```

**Comment by eduard93** [comment]
So, no way without %DB_CACHESYS I guess

**Comment by ZitRos** [comment]
Please, build the latest terminal from master and verify if it works for 2016.1 with normal security option.

If it is, let's make this issue resolved!

Thank you!

**Comment by eduard93** [comment]
Tested
