### ISSUE TITLE
How close the session

### ISSUE THREAD

**Issue by jjzamoram** [intersystems-ru/webterminal#60]
How i can close the session in the webterminal?, with the letter "h" close the conection but when I update my page with "F5" the session is  connecting again.

**Comment by ZitRos** [comment]
Hello!
Web Terminal does not save it's state when you press F5: all local variables are removed.
But if you mean HTTP session, it is fully controlled by CSP gateway, and sessions are alive until you clear any cookies and browser's cache. What's the purpose of session reset?

**Comment by ZitRos** [comment]
Do you think Web Terminal should implement "session reset" somehow?
For example, I suggest adding `/logout` command to change the user.
Is this what you meant?

P.S. Currently I think Chrome incognito mode would allow you to do so.

**Comment by eduard93** [comment]
`do %session.Logout(1)` should do the trick

**Comment by ZitRos** [comment]
Edward, do you think we need to make a terminal shortcut for this, like
`/logout`?

**Comment by eduard93** [comment]
Maybe automatically send it to a server on tab close/page reload?

**Comment by ZitRos** [comment]
I think it shouldn't be send automatically. The only user I use is SYSTEM,
but I reload the tab frequently. Here I see `logout` as a useful thing, do
you see this also useful?

**Comment by eduard93** [comment]
It's just I also see no particular intention to use it - what for? 
One use case I can see is closing webterminal session on unsecured computer but that's a bad idea in the first place. @jjzamoram any thought on why we need this feature?

**Comment by ZitRos** [comment]
Closed due to discussion inactivity.
@jjzamoram, please, reopen the issue if you think we need to implement something more than just `do %session.Logout(1)`. Thanks!

**Comment by ZitRos** [comment]
Getting back to this question, @eduard93, `%session.Logout(1)` doesn't seem to work. Even when I made a test REST URL handler:
```
ClassMethod LogOut() As %Status
{
    do %session.Logout(1)
    write "OK"
    return $$$OK
}
```

It responds `"OK"`, but indeed doesn't ask me to log in after I reload the page and continues to work under the user I logged in first time. (`Cache for Windows (x86-64) 2016.2 (Build 636U)`) Do you know any ways to fix this?

**Comment by eduard93** [comment]
That depends upon your security setup.

**Comment by ZitRos** [comment]
@eduard93, so is there a way to log out on minimal security installations?

**Comment by eduard93** [comment]
After you log out, you'll still be an UnknownUser with access to a terminal, so no. You can remove roles from UnknownUser I suppose, but that might be not a good idea.

**Comment by ZitRos** [comment]
@eduard93,

Not this case:
```
ClassMethod LogOut() As %Status
{
    write $username
    do %session.Logout(1)
    write " -> ", $username
    return $$$OK
}
```

Results with `_SYSTEM -> _SYSTEM`

**Comment by eduard93** [comment]
Does next request return  _SYSTEM?

**Comment by ZitRos** [comment]
Yes.

**Comment by ZitRos** [comment]
@jjzamoram, now WebTerminal v`4.0.0-beta.8` supports `/logout` command, you can update to the latest version or download WebTerminal [here](http://intersystems-ru.github.io/webterminal/#downloads).

**Comment by eduard93** [comment]
It it solved on server or client side?
Can you please point me to  the specific commits.

**Comment by ZitRos** [comment]
Hi @eduard93, 
It was a client problem, with browser's basic authentication cache. See [my community question](https://community.intersystems.com/post/how-log-out-web-application) for more details.

**Comment by eduard93** [comment]
@ZitRos thank you!
