### ISSUE TITLE
Cache Web Terminal with apache webserver

### ISSUE THREAD

**Issue by paul-goggin** [intersystems-ru/WebTerminal#62]
Is it possible to access the web terminal with apache web server?

i get an 404 error when i try to access

![image](https://cloud.githubusercontent.com/assets/13796429/15323199/cb2375aa-1c38-11e6-96e1-b2e264cf30d9.png)

![image](https://cloud.githubusercontent.com/assets/13796429/15323236/f9174d6a-1c38-11e6-9ebe-40bdc9d9173c.png)

**Comment by eduard93** [comment]
There should be absolutely do difference. 
Can you access the terminal at 57772 port (internal apache)?

**Comment by paul-goggin** [comment]
The internal webserver is turned off
![image](https://cloud.githubusercontent.com/assets/13796429/15327114/41bded3a-1c48-11e6-885d-fa5ee9010f90.png)

**Comment by adaptun** [comment]
@paul-goggin can you provide csp settings in httpd.conf? It seems that apache does not route this request to CSP Gateway.

**Comment by paul-goggin** [comment]
#### BEGIN-CSP-SECTION() ####
#
LoadModule csp_module_sa "C:/TC1/CSPGateway/bin/CSPa22.dll"
LoadModule cspsys_module_sa "C:/TC1/CSPGateway/bin/CSPa22Sys.dll"
#
CSPModulePath C:/TC1/CSPGateway/bin/
#
Alias /csp/ "C:/TC1/cache/csp/"
Alias /ctest/csp/ "C:/TC1/cache/csp/"
Alias /cache/csp/ "C:/TC1/cache/csp/"
#
<Directory "C:/TC1/cache/csp">
	AddType application/x-csp .csp .cls .zen .cxw
	AllowOverride None
	Options MultiViews FollowSymLinks ExecCGI
	Order allow,deny
	Allow from all
	<FilesMatch "\.(log|ini|pid|exe)$">
		Deny from all
	</FilesMatch>
</Directory>
#
<Location "/csp/bin/Systems/">
	SetHandler cspsys-handler-sa
</Location>
#
<Location "/csp/bin/RunTime/">
	SetHandler csp-handler-sa
</Location>
#
<Location /csp>
	CSP On
	SetHandler csp-handler-sa
</Location>
#
AddHandler csp-handler-sa csp cls zen cxw
#
#### END-CSP-SECTION ####

**Comment by adaptun** [comment]
@paul-goggin with provided conf apache forwards to CSP Gateway only requests for pages that start with /csp:

    <Location /csp>
        CSP On
        SetHandler csp-handler-sa
    </Location>

You might either place /webterminal into /csp/webterminal web-app or configure apache to send /webterminal requests to CSP Gateway also.

_Maybe_ adding following will help (but I'm not sure):

    <Location /webterminal>
        CSP On
        SetHandler csp-handler-sa
    </Location>

**Comment by paul-goggin** [comment]
That has worked i am now able to open the terminal but i am now getting an error message when i try to log in 

> WebSocket connection error (ws://127.0.0.1:51080/terminalsocket/WebTerminal.Engine.cls). Trying to connect again in 10 seconds...
> WebSocket connection closed. Code 1006, reason: .

**Comment by eduard93** [comment]
Add
`
<Location /terminalsocket>
    CSP On
    SetHandler csp-handler-sa
</Location>
`

**Comment by paul-goggin** [comment]
It is working now

Thanks for the help
