### ISSUE TITLE
Send a Command to an embedded Web Terminal

### ISSUE THREAD

**Issue by mtmccarthy** [intersystems-ru/webterminal#68]
When the Web Terminal is embedded within a web page, say within an iframe, it can be helpful for the outer web page to have the ability to send commands to within the web terminal in place of a user.

This can helpful for a variety of reasons, most notably to:

1) Setup an environment for the user.
2) Allow the user to leave and come back. In this case the program using the web terminal would keep track of commands needed to place the user back in the environment that they left off. With their variables set to the same names.

If the API could implement a feature such as the following:

terminal.sendCommand(commandText)

Where "commandText" would be a string that would be sent to the terminal and executed as if a user had manually entered this string within the iframe.

Example:

In order to set up the environment correctly, on startup the terminal must store a variable named "Username" that is set to a predefined value.

In the javascript a user would enter the following code:

```js
iFrame.addEventListener("load", function () {
  iFrame.contentWindow.onTerminalInit(myInitHandler); // handle terminal initialization
});

function myInitHandler (terminal) {
  terminal.sendCommand("set Username = \"exampleUser\" ");
  //This would create a variable string called Username that the user could use on startup
}
```

**Comment by ZitRos** [comment]
Hello Matthew @mtmccarthy!

Thank you for the issue. The `terminal.sendCommand`, may be named as `terminal.execute`, is pretty easy to implement. However, it should take some additional options to be universal `terminal.execute(command, options)`. Example:

```js
terminal.execute("set Username = \"exampleUser\"", { // default values are assigned below
  echo: false, // print command on the screen
  prompt: false, // ask user for input after execution
});
```

When I was creating a plan for CWTv4, I was thinking about restoring terminal sessions as a WebTerminal feature. At least, not to kill a terminal server process for a while, and allow user to connect to the previously opened session. It seems that it is almost exactly the thing you want to implement, isn't it?

**Comment by mtmccarthy** [comment]
I believe this should cover everything we need. Thanks!

**Comment by ZitRos** [comment]
OK, let this issue track terminal API extension with `execute` function. Restoring terminal sessions should go into another issue.

**Comment by mtmccarthy** [comment]
Thanks again for your work on this. Do you have an estimate for how much more time this will take?

**Comment by ZitRos** [comment]
Hello Matt!

I am working hard on intelligent autocomplete for WebTerminal right now, and I am close to say that the basic work is done. I don't want to push "braking" version of code right now, and I think I need one more day to get all of this landed.

So, you can expect this issue to be closed tomorrow.

**Comment by mtmccarthy** [comment]
Thank you for the quick reply! We really appreciate all the work you've put in.

**Comment by ZitRos** [comment]
Done with 6197815a60320f3ec7466d279fcd91da6e14bfc1.
