### ISSUE TITLE
SQL mode sometimes results as unknown response

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/webterminal#70]
Possibly the empty arrays are not correctly formed in JSON:

```
USER:SQL > DELETE FROM Simple.Demo
Unable to parse server response: {"_cb":1,"d":{"data":,"headers":},"h":""}
```

**Comment by eduard93** [comment]
`data` and `headers` fields values are not a dynamic objects (probably normal objects)

**Comment by ZitRos** [comment]
I think so.

**Comment by ZitRos** [comment]
So this JSON output is generated when
```
set obj.headers = ##class(%ListOfDataTypes).%New()
set obj.data = ##class(%ListOfDataTypes).%New()
```

Are empty. I would call it yet another Caché JSON issue.

**Comment by eduard93** [comment]
How do you serialize to JSON?

**Comment by ZitRos** [comment]
This way: `do ##class(%ZEN.Auxiliary.jsonProvider).%ObjectToJSON(obj,,,"aeos")`

I ended up by removing that arrays from JSON if they are empty.
