### ISSUE TITLE
Cache Web Terminal does not use startup Tag^Routine

### ISSUE THREAD

**Issue by paul-goggin** [intersystems-ru/webterminal#73]
I have set up a startiup Tag^Routine in the System Management portal, but when I use CWT it does not start the routine, however it will change the namespace when the Startup Namespace option is selected
![image](https://cloud.githubusercontent.com/assets/13796429/19925541/4e29157a-a0e8-11e6-855a-0ad28d59bfc0.png)

![image](https://cloud.githubusercontent.com/assets/13796429/19925564/711e7b38-a0e8-11e6-83ee-e513f9b73c7d.png)

**Comment by ZitRos** [comment]
Hello Paul!

Thank you for this issue report. Definitely WebTerminal doesn't parse Startub Tag^Routine user configuration field.

I will check this.

**Comment by ZitRos** [comment]
@paul-goggin, please, check the WebTerminal v`4.0.0-beta.7`, I have added a support for startup routine. Please, confirm if the issue is solved and if it is, go to close it.
Thank you!

**Comment by paul-goggin** [comment]
@ZitRos This is now working as expected
