### ISSUE TITLE
Arrow keys sending the up and down commands

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/webterminal#74]
I am creating this issue to clarify the issue reported by @paul-goggin, which puts the next:

> In the latest version of Cache Web Terminal (4.0 Beta 5) is it possible to change the up and down cursor keys to stop showing the history and just send the up and down command?

> I will check this today
>
> Just to clarify, do you mean the history appears in the character read mode ( read *char ), when you press up arrow, but instead it must send UP key to the server?

> Yes, that is correct,
> Thanks for your help,

I have checked this today, and got a result, which seems to be correct:

![2016-11-02_145020](https://cloud.githubusercontent.com/assets/4989256/19929393/cdec0cae-a10b-11e6-9a7d-48803eac4b73.png)

@paul-goggin, could you please suggest a set of commands which demonstrate the issue? Thank you!

**Comment by paul-goggin** [comment]
Hi, 
I have the code which is called for prompts
`R %AN S AZB=$ZB`
`I $A($E(AZB,1))=27 S AZB=$P(AZB,"[",2) S %AN=$S(AZB="B":"+",AZB="A":"-",AZB="C":"++",AZB="D":"--",1:%AN) G:%AN=""`

and based on the result of %AN the prompt will run a function
G:%AN="-" END

**Comment by ZitRos** [comment]
@paul-goggin, by running this command in Caché term, I see the read prompt, and when you press the up/down arrow the history comes up (`R %AN`). So there is nothing different in Caché Web Terminal, all is the same. What is the expected behavior and does it differ from Caché term one?

**Comment by ZitRos** [comment]
@paul-goggin, have you any updates on this?

**Comment by ZitRos** [comment]
Closed due to inactivity.
