### ISSUE TITLE
D ^%GD has bad results

### ISSUE THREAD

**Issue by MartinFukatko** [intersystems-ru/webterminal#76]
I've tried to write down all global names in namespace by system utility ^%GD and I've got a mismatch on webterminal screen. Try it yourself
>DO ^%GD
and all defaults up to end.

Martin

**Comment by ZitRos** [comment]
Definitely see this issue. Thanks for reporting. This will take a while to investigate a problem.

**Comment by ZitRos** [comment]
Okay, I have pushed some changes to `v4.0.0-beta.12` which will vanish the formatting issues. But there is still one issue (#77) with the device detection, which causes WebTerminal to clear the screen at the end. I hope this will become resolved in a close future, but for now at least you can see the ^%GS's output by scrolling the screen up after the execution.

Thanks for reporting! The bug with clearing screen at the end of ^%GD's execution now goes to "the issue of fortune" #77.
