### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ThomLu** [intersystems-ru/webterminal#82]
Hello,

I was thrilled reading about this project and possibility to access a terminal via web interface. I have installed it using your guide, but the webapp is not working. It displays a http basic login dialog and after a succesfull login it just displays a black screen without any error or text on it.

Any help is appreciated.

$zv: Cache for UNIX (Red Hat Enterprise Linux for x86-64) 2016.2.1 (Build 803U) Wed Oct 26 2016 12:31:26 EDT

**Comment by eduard93** [comment]
What's your security setup?
have you tried logging in with user with %All to make sure that it's not a roles issue?

**Comment by ZitRos** [comment]
Hello ThomLu!

Thank you for sharing your experience!

However, some terminal application, especially ones which use VT240 escape
sequences may not properly work in WebTerminal for now, and I am doing a
lot to make them work every day.

To understand what does not work properly in your application, I need the
minimal technical details about the issue, or the application's source code
to investigate the problem by myself.

Are there any more details you can share with me? Thank you!

**Comment by ThomLu** [comment]
The Ensemble was installed using normal security setup. The user has %All (it is the System administrator).

**Comment by eduard93** [comment]
@ThomLu and he does not have startupRoutine, correct?
What browser do you use?

**Comment by ThomLu** [comment]
Hi ZitRos - I used the term webapp for WebTerminal application under Security configuration in Caché.
So what I did:
- imported and compiled your code (XML) into Ensemble using Ensemble Management Portal.
- it was finished OK.
- used http://<ip>/terminal/ to access the WebTerminal
- no luck here - see above.
- there is no error shown in a browsers konsole (I am usig Safari and Chrome), there is also no error log in Ensemble Application Log or System Log

**Comment by eduard93** [comment]
![webapp](https://cloud.githubusercontent.com/assets/5127457/22263405/6bf70dda-e285-11e6-929a-028c31026a86.PNG)
@ThomLu do you see these two Web Applications locally?

**Comment by ThomLu** [comment]
No there is no startup routine for the user. I normaly use the user to access EMP, Atelier and Studio. The browser is Safar (latest) and G Chrome (latest)

**Comment by ZitRos** [comment]
@ThomLu, thanks! But it is more important **which** application you are trying to run undre WebTerminal. The main point for me here is to figure out which part of the code of **your** application does not work correctly in WebTerminal.

If you can share any of related details, you are welcome! Thanks!

**Comment by ThomLu** [comment]
@eduard93 yes it is exactly what I am seeing.
@ZitRos I am not trying to use any application - I even do not get command prompt in the WebTerminal so I am not able to run anything under WebTerminal. See the screenshots.

<img width="1037" alt="webterm_i" src="https://cloud.githubusercontent.com/assets/25330504/22263640/6f605d2e-e275-11e6-8a15-c62137f66c75.png">
<img width="878" alt="webterminal_ii" src="https://cloud.githubusercontent.com/assets/25330504/22263641/6f60e9ec-e275-11e6-9bb4-f37c3aef3ea5.png">

**Comment by ThomLu** [comment]
After I enter user`s credentials, there is this text:
Terminal load complete. Getting auth key...

This text disapears after ~0,5 seconds and the screen remains black.

**Comment by eduard93** [comment]
Is UnknownUser enabled? Can you give him %All temporally and open webterminal from new private window?

**Comment by ThomLu** [comment]
@eduard93 That solved the problem! This is configuration is required by the WebTerminal?

**Comment by ThomLu** [comment]
@eduard93 UnknownUser does not have to have %All - I just removed this role form the user and it also works.

**Comment by eduard93** [comment]
UnknownUser should be enabled. %All is not a requirement.

**Comment by ZitRos** [comment]
@ThomLu, ah got you. Okay, so the thing is in '/terminalsocket' application — it must be available for non-authenticated users like UnknownUser without password protection. This is the only way how to enable WebSocket to connect to the server (at least that I have discovered). So that's why I suppose it was happening. Thanks for submitting the issue! You are improving our knowledge base.

**Comment by ThomLu** [comment]
Thanks a lot for your lightning support! 
Is it a production ready solution? I mean from the perspective of security - I do not know what /terminalsocket application does but it has %DB_USER and %DB_CACHE application roles - so any unauthenticated user have these roles through this application...

**Comment by eduard93** [comment]
These roles are required to login user.
