### ISSUE TITLE
Additional Escape Sequence 

### ISSUE THREAD

**Issue by denhamson** [intersystems-ru/webterminal#84]
Escape sequence <ESC>[m  not working, should be equivalent to <ESC>[0m

**Comment by ZitRos** [comment]
Thanks for reporting! Expect this to be fixed soon.

**Comment by ZitRos** [comment]
Fixed in WebTerminal v4.2.3, please update. Thanks for reporting!
![2017-02-07_174027](https://cloud.githubusercontent.com/assets/4989256/22698196/92fdc400-ed5c-11e6-9da1-048fae0471a0.png)
