### ISSUE TITLE
Problem with Escape Sequence Clear Display to End?

### ISSUE THREAD

**Issue by denhamson** [intersystems-ru/webterminal#86]
The expected behaviour for clear display to end or x364 /ED(0) is to clear from current position to end of display area.  

If the cursor is at column 41 on row 12 I would expect the second half of row 12 to be cleared and then all of rows 13 onwards to be cleared. 

Actual behaviour is to clear all of row 12.

**Comment by ZitRos** [comment]
Thanks for reporting! Would check this as soon as possible.

**Comment by ZitRos** [comment]
The `Esc[1J` sequence doesn't work properly as well. Will fix this for the next terminal version, expect the fix soon.

Thanks!

**Comment by ZitRos** [comment]
Fixed by d4977c34feea5484caa82319640a35dfb4ed73fa. Expect new version to be released today and please confirm that issue now gone.

**Comment by ZitRos** [comment]
New version is now in production, please update and check if these escape sequences are fixed.

Thanks!

**Comment by ZitRos** [comment]
Closing due to no response provided. The issue was fixed.
