### ISSUE TITLE
Is it possible that some %ROUTINES are OS sensitive?

### ISSUE THREAD

**Issue by masterbeer** [intersystems-ru/webterminal#93]
This might sound weird but I believe there is something affecting ^%G when running over Linux.
All Windows machines I've tried were just fine. 
But when using Linux it hangs when trying to get out of ^%G.
I can access it, search for globals but when I type "blank return" to exit it hangs and I lose the terminal.

Points I notice:

- It gives "WebSocket Read Operation timed-out" **right after I hit enter.**
- The process is ending (I believe before it should) **right after I hit enter.**
- It is getting stuck here: https://gist.github.com/masterbeer/f7c6be106c86befe5dd57377ec866548, with could be because the process does not exist and is not throwing error.

As I'm still making sense of the code I can not be more detailed on the possible cause. But I hope you understand.

**Comment by ZitRos** [comment]
Hello @masterbeer! Thanks for reporting. The issue is confirmed to exists.

**Comment by masterbeer** [comment]
Ok, thx!!

**Comment by ZitRos** [comment]
OK, I have found a reason causing this. This command being executed in WebTerminal under Windows does nothing:

```
close 0
```

However, on Unix machines it terminates child process...

**Comment by ZitRos** [comment]
New version is now live, please confirm that utility is fixed and everything works fine. Thanks for reporting!

**Comment by masterbeer** [comment]
You nailed it! Working fine. Thank you.
